server.port=8084
spring.application.name=ms-suscripciones

spring.datasource.url=jdbc:mysql://localhost:3306/db_gym_suscripciones?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA & Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Comunicación Inter-MS
ms.miembros.url=http://localhost:8083

# Eureka (Solo si lo estás utilizando para registro, si no, puedes omitirlo)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Seguridad
jwt.secret=TXV5TGdyYVNlZ3VyYVBhcmFHeW1TeW5jMjAyNkNvbnRyYXNlbmE=